---
title: "ANOVA_test_Wolffia"
output:
  pdf_document: default
  html_document: default
date: '2024-03-02'
---

```{r setup, include=FALSE}
rm(list=ls())

#install.packages("knitr")
library(knitr)
knitr::opts_chunk$set(echo = TRUE)
library(emmeans)
```

# Read in original dataset 
```{r}
Wolffia <- read.csv("WGdataset_AoBPlants.csv")
str(mydata)
```


## Process data
#
```{r}

## Sum Alive and Dead Frond Count

Wolffia$Frond_count <- Wolffia$Frond_count_1 + Wolffia$Frond_count_2 + Wolffia$Frond_count_3
Wolffia$Dead_count <- Wolffia$Dead_frond_count_1 + Wolffia$Dead_frond_count_2 + Wolffia$Dead_frond_count_3
```

## Frond Count Analysis
```{r}

# select temps for analysis
# for constant treatments
temps1=c(14.0, 20.0,25, 26.5,28.5,31.5, 37)
# for fluctuating treatments
temps2=c(26.5,31.5)

# grab constant data
test_data1=Wolffia[Wolffia$Mean_temperature%in%temps1,]
test_data1=test_data1[test_data1$Treatment=="constant",]

# grab fluctuating data
test_data2=Wolffia[Wolffia$Mean_temperature%in%temps2,]

# change numeric temps to factor
test_data1$Mean_temperature=format(test_data1$Mean_temperature, nsmall=1) 
test_data2$Mean_temperature=format(test_data2$Mean_temperature, nsmall=1) 

test_data1$Mean_temperature <- as.factor(test_data1$Mean_temperature)
test_data2$Mean_temperature <- as.factor(test_data2$Mean_temperature)
```

```{r}
# subsample and analysis test_data2
n <- 6 
index <- 1:length(temps2)
fun <- function(x) sample(x, n)
a <- by(test_data2$Frond_count, list(test_data2$Mean_temperature,test_data2$Treatment), FUN = fun)


df <- data.frame(Temp=as.factor(c(rep(c(rep(26.5, 6), rep(31.5, 6)),2))), Treat=c(rep("constant", 12), rep("fluctuating", 12)))
df$Frond_count <- unlist(a)

b <- by(test_data2$Dead_count, list(test_data2$Mean_temperature,test_data2$Treatment), FUN = fun)
df$Dead_count <- unlist(b)

#complete anova test_data2
Frond_anov_x=glm(Frond_count~Temp*Treat, df, family="poisson")
summary(Frond_anov_x)


```

```{r}
#Create interaction plot

jpeg(filename = "Fig5_interactionplot.jpeg", 
     width = 8, 
     height = 8, 
     units = "cm", 
     res = 600)

# calc mean and standard deviation test_data2
barmean=aggregate(df$Frond_count~df$Temp*df$Treat, FUN=mean)
barstd=aggregate(df$Frond_count~df$Temp*df$Treat, FUN=sd)
barsum=aggregate((df$Frond_count>0)~df$Temp*df$Treat, FUN=sum)

# graph test_data2

graph=interaction.plot(df$Temp, df$Treat, df$Frond_count,bty="l",ylim=c(40,111),
                 legend=FALSE,las=1,
                 ylab = "Live fronds",
 # xlab = "Temperature (ºC)",
 xlab="",
  trace.label = "Treatment",
  col = c("#0198f9", "#f95801"),pch=c(1,6),
  lty = c(1,2),
  lwd = 0, 
  cex.axis=.8, 
  #cex.lab=1.3
  )

title(xlab="Temperature (ºC)", line=2.3, cex.lab=1)

points(c(1,2),barmean[1:2,3], col = "#0198f9", pch=16,cex=1.4)
lines(barmean[1:2,3], col = "#0198f9", lwd=2)
points(barmean[3:4,3], col="#f95801", lwd=2, pch=17, cex=1.4)
lines(barmean[3:4,3], col="#f95801",lwd=2, lty=2)

points(rep(1.07,6),df$Frond_count[df$Temp=="26.5" & df$Treat=="constant"], col = "#0198f9", pch=1,cex=1.)

points(rep(2.07,6),df$Frond_count[df$Temp=="31.5" & df$Treat=="constant"], col = "#0198f9", pch=1, cex=1.)

points(rep(.93,6),df$Frond_count[df$Temp=="26.5" & df$Treat=="fluctuating"], col = "#f95801", pch=2,cex=1.)

points(rep(1.93,6),df$Frond_count[df$Temp=="31.5" & df$Treat=="fluctuating"], col = "#f95801", pch=2,cex=1.)

legend("top", legend=c("constant", "fluctuating"), col = c("#0198f9", "#f95801"),
  lty = c(1,2), 
  cex=.7,
  lwd = 1.2, bty="n",pch=c(1,2), title="Treatment")


dev.off()

```


# Barplot for frond count
```{r}

# subsample test_data1
n <- 5 
index <- 1:length(temps1)
fun <- function(x) sample(x, n)
a <- by(test_data1$Frond_count , list(test_data1$Mean_temperature), FUN = fun)

b <- by(test_data1$Dead_count , list(test_data1$Mean_temperature), FUN = fun)


df1=do.call(rbind, 
        lapply(names(a), function(i){
          data.frame(Temp = i, a[[ i ]], b[[i]])
        }))
colnames(df1)[2]="Frond_count"
colnames(df1)[3]="Dead_count"



```



## Live Frond

```{r}
#complete anova for live
Frond_anov=glm(Frond_count~Temp, 
              family="poisson",data=df1)
summary(Frond_anov)

#emmeans(Frond_anov, "Temp")$contrasts
options(emmeans = list(Frond_anov = "satterthwaite",  contrast = list(infer = c(TRUE, TRUE))))


ems=(emmeans(Frond_anov, "Temp", type = "response",adjust="none"))
ems=as.data.frame(ems)
emmeans(Frond_anov, pairwise ~ Temp)

```

```{r graph1}

# graph means and std
graph <- barplot(height = ems$rate, names = ems$Temp,las=1,
 ylim = c(0,112), xlab = "Temperature (ºC)", ylab = "Live fronds", col = "dark green", cex.lab=1.3, cex.axis=1., cex.names=1.)
arrows(x0 = graph, y0 = ems$rate - ems$SE,x1 = graph, y1 = ems$rate + ems$SE, length = 0.05, code = 3, angle = 90)
text(graph[7]+.35, 108, "a", cex=1.8)

segments(x0=graph[4]-.4, x1=graph[6]+.4, y0=90,y1=90, lwd=2 )
text(graph[4]-.25, 94., "c", cex=1.2)

segments(x0=graph[2]-.4, x1=graph[3]+.4, y0=90,y1=90, lwd=2 )
text(graph[2]-.25, 94.75, "b", cex=1.2)

segments(x0=graph[1]-.4, x1=graph[1]+.4, y0=90,y1=90, lwd=2 )
text(graph[1]-.25, 94, "a", cex=1.2)

segments(x0=graph[7]-.4, x1=graph[7]+.4, y0=90,y1=90, lwd=2 )
text(graph[7]-.25, 94, "a", cex=1.2)

```

# Dead Fronds

```{r}
#complete anova
Dead_anov=glm(Dead_count~Temp, 
              family="poisson",data=df1)
summary(Dead_anov)

emsD=emmeans(Dead_anov, "Temp", type = "response", adjust="none")
emmeans(Dead_anov, pairwise ~ Temp)
emsD=as.data.frame(emsD)
```

```{r graph2}

# graph means and std
graph <- barplot(height = emsD$rate, names = emsD$Temp,
 ylim = c(0,29), xlab = "Temperature (ºC)", ylab = "Dead fronds", col = "dark goldenrod", cex.lab=1.3, cex.names = 1., cex.axis=1., las=1)
arrows(x0 = graph, y0 = emsD$rate - emsD$SE,x1 = graph, y1 = emsD$rate + emsD$SE, length = 0.05, code = 3, angle = 90)
text(graph[7]+.35, 28, "b", cex=1.8)
segments(x0=graph[1]-.4, x1=graph[2], y0=20,y1=20, lwd=2 )
text(graph[1]-.3, 21, "a", cex=1.2)
segments(x0=graph[2]-.6, x1=graph[4]-.1, y0=21,y1=21., lwd=2 )
text(graph[2]-.3, 22.25, "b", cex=1.2)
segments(x0=graph[3]-.2, x1=graph[6]+.4, y0=22,y1=22, lwd=2 )
text(graph[3], 23, "c", cex=1.2)
segments(x0=graph[7]-.4, x1=graph[7]+.4, y0=23,y1=23, lwd=2 )
text(graph[7]-.3, 24.25, "d", cex=1.2)


```

## Two panal plot

```{r multigraph, echo=FALSE}
jpeg(filename = "Fig4_barplot.jpeg", 
     width = 17, 
     height = 11, 
     units = "cm", 
     res = 600)
par(mfrow = c(1, 2))

<<graph1>>
<<graph2>>
  dev.off()
```